[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/monttj/computational-physics/blob/2021/ComPhy-1-Python.ipynb)

# Introudction to Python

In this exercise, you will learn the basics of python computer language. You can either login to the dedicated server and run the jupyter or just click the button above to switch to Colab. 

### Excute

In [ ]:
ls *.py

myParticle.py


In [ ]:
cat hello_python.py

cat: hello_python.py: No such file or directory


##### answer:
```
#!/usr/bin/env python

print "Hello world!"
```

In [ ]:
!python hello_python.py

python3: can't open file 'hello_python.py': [Errno 2] No such file or directory


##### answer:
```
Hello world!
```

### Print

In [ ]:
a = "Hello World!"

In [ ]:
print (a)

Hello World!


In [ ]:
myname = "Computational Physics"
print ("My name is = ", myname)

My name is =  Computational Physics


### Indent

In [ ]:
#this is not correct
#CORRECT ME!
x = 3
y = 4
z = x + y 
print ("3 + 4 is {}".format(z))

3 + 4 is 7


##### answer:
```
3 + 4 is 7
```


### Assignment

In python which is a dynamically typed language, we don't need to specify the type of a variable. This is one of the main difference compared to c++. 

We will create a variable by assigning a value to the variable below and will check the type:

In [ ]:
# variable assignments
x = 1.0
type(x)

float

In [ ]:
#fix this and make the output true
type(x) is float

True

##### answer:
```
True
```

In [ ]:
#can use the function
isinstance(x, float)

True

##### answer:
```
True
```

In [ ]:
x = 1
type(x)

int

In [ ]:
x = "hello"
type(x)

str

In [ ]:
x = True #can also be False
type(x)

bool

In [ ]:
x = 1.0 - 1.0j
type(x)

complex

In [ ]:
print (x)

(1-1j)


In [ ]:
print(x.real, x.imag)

1.0 -1.0


In [ ]:
y = bool(x.real)

In [ ]:
print (x.real, ":", y)

1.0 : True


In [ ]:
y = bool(x.imag)

In [ ]:
print (x.imag, ":", y)

-1.0 : True


In [ ]:
import types

# print all types defined in the `types` module
print(dir(types))

['AsyncGeneratorType', 'BuiltinFunctionType', 'BuiltinMethodType', 'ClassMethodDescriptorType', 'CodeType', 'CoroutineType', 'DynamicClassAttribute', 'FrameType', 'FunctionType', 'GeneratorType', 'GetSetDescriptorType', 'LambdaType', 'MappingProxyType', 'MemberDescriptorType', 'MethodDescriptorType', 'MethodType', 'MethodWrapperType', 'ModuleType', 'SimpleNamespace', 'TracebackType', 'WrapperDescriptorType', '_GeneratorWrapper', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_calculate_meta', 'coroutine', 'new_class', 'prepare_class', 'resolve_bases']


### Math operator

This code will give the sum of x and y. The answer should be 7. 

In [ ]:
#summation
x = 3
y = 4
z = x + y
print ("sum =", z)

sum = 7


In [ ]:
#subtraction
z = x - y
print ("subtraction = ", z)

subtraction =  -1


In [ ]:
#multiplication
z = x*y
print ("multiplication = ", z)

multiplication =  12


In [ ]:
#division
z = x/y
print ("z = ", z)

z =  0.75


In [ ]:
#division
x = 3.0
y = 4.0
z = x/y
print ("z = ", z)

z =  0.75


In [ ]:
#modulus
x = 3.0
y = 1.1
reminder = x%y
print ("reminder = ", reminder)

reminder =  0.7999999999999998


In [ ]:
quotient = x//y
print ("quotient = ", quotient)

quotient =  2.0


In [ ]:
#exponent
z = x**3
print ("z = ", z)

z =  27.0


In [ ]:
#import math to be able to use the math function
import math
x = math.cos(2 * math.pi) #math.pi = 3.14159265359
print ("cos(2*3.14159265359) = ", x)

cos(2*3.14159265359) =  1.0


We can choose to import all symbols to the current namespace. In this way, we can use the math modules without using the prefix "math":

In [ ]:
#import math to be able to use the math function
from math import *
x = cos(2 * pi) #math.pi = 3.14159265359
print ("cos(2*3.14159265359) = ", x)

cos(2*3.14159265359) =  1.0



This is very convenent but sometimes it can be confusing with the symbols as it can also be used in other places. Usually it is better to keep the namespaces. This would elimate the cofusing problems with the name space collisions. 
This pattern can be very convenient, but in large programs that include many modules it is often a good idea to keep 

Otherwise, we can chose to import only a few selected symbols from a module by explicitly listing which ones we want to import instead of using the wildcard character *:

In [ ]:

from math import cos, pi
x = cos(2 * pi) #math.pi = 3.14159265359
print ("cos(2*3.14159265359) = ", x)

cos(2*3.14159265359) =  1.0


You can check what is available in math library with following lines:

In [ ]:
a = log(10)
print ("log(10) = ", a)
b = log(10,2)
print ("log(10,2) = ", b)

log(10) =  2.302585092994046
log(10,2) =  3.3219280948873626


In [ ]:
import math

print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


### Strings

In [ ]:
s = "Hello world"
type(s)

str

In [ ]:
# length of the string: the number of characters# length 
len(s)

11

In [ ]:
# replace a substring in a string with something else
s2 = s.replace("world", "Physics")
print(s2)

Hello Physics


In [ ]:
s[0]

'H'

In [ ]:
s[0:5]

'Hello'

In [ ]:
s[4:5]

'o'

In [ ]:
s[:5]

'Hello'

In [ ]:
s[6:]

'world'

In [ ]:
s[:]

'Hello world'

We can also define the step size [start:end:step]:

In [ ]:
s[::1]

'Hello world'

In [ ]:
s[::3]

'Hlwl'

In [ ]:
a = "Computational"
b = "Physics"
print (a,b)

Computational Physics


In [ ]:
print (a, b, 2, "is", True)

Computational Physics 2 is True


In [ ]:
print (a+b)

ComputationalPhysics


In [ ]:
print ("value = %f" % 1.0)

value = 1.000000


In [ ]:
s = "value1 = %.2f. value2 = %d" % (3.1415, 1.5)
print (s)

value1 = 3.14. value2 = 1


### List

In [ ]:
l = [1,2,3,4]

print (type(l))
print (l)

<class 'list'>
[1, 2, 3, 4]


In [ ]:
print (l[1:3])
print (l[::2])

[2, 3]
[1, 3]


In [ ]:
l[2]

3

In [ ]:
nested_list = [[1,2], [3,4]]

In [ ]:
print (nested_list)

[[1, 2], [3, 4]]


In [ ]:
start = 0
stop = 10
step = 1
l = range(0,10,1)
print (l)

range(0, 10)


In [ ]:
l = range(-10,10)
print (l)

range(-10, 10)


In [ ]:
# sorting lists
l = [9,1,10,3,4,6,2,5,7,8]
print (l)
l.sort()
print (l)

[9, 1, 10, 3, 4, 6, 2, 5, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
# create a new empty list
l = []

# add an elements using `append`
l.append("P")
l.append("H")
l.append("Y")

print (l)

['P', 'H', 'Y']


In [ ]:
l[0] = "H"
l[1] = "Y"
l[2] = "U"

print (l)

['H', 'Y', 'U']


In [ ]:
l.insert(3, "P")
l.insert(4, "H")
l.insert(5, "Y")
print (l)

['H', 'Y', 'U', 'P', 'H', 'Y']


In [ ]:
l.remove("H")
print (l) 

['Y', 'U', 'P', 'H', 'Y']


In [ ]:
del l[1]
print (l)

['Y', 'P', 'H', 'Y']


### Dictionaries

In [ ]:
params = {"mass" : 3,
          "distance" : 2.0,
          "gravity" : 9,}

print (type(params))
print (params)

<class 'dict'>
{'mass': 3, 'distance': 2.0, 'gravity': 9}


In [ ]:
print("mass = " + str(params["mass"]))
print("distance = " + str(params["distance"]))
print("gravity = " + str(params["gravity"]))

mass = 3
distance = 2.0
gravity = 9


In [ ]:
params["mass"] = 10
params["distance"] = 5

# add a new entry
params["force"] = params["mass"]*params["gravity"]

print("mass = " + str(params["mass"]))
print("distance = " + str(params["distance"]))
print("gravity = " + str(params["gravity"]))
print("force = " + str(params["force"]))

mass = 10
distance = 5
gravity = 9
force = 90


### Conditional statement

In [ ]:
# equality
2 == 1

False

In [ ]:
2 > 1, 2 < 1

(True, False)

In [ ]:
# objects identical?
a = b = 3

a is b

True

Program blocks are defined by their indentation level.

In [ ]:
if sum == 55:
    print ("Correct answer!")
else:
    print ("Wrong answer!")

Wrong answer!


In [ ]:
if True and False:
    print ("True and False = True")
else:
    print ("True and False = False")

True and False = False


In [ ]:
if True or False:
    print ("True or False = True")
else:
    print ("True or False = False")

True or False = True


In [ ]:
if not False:
    print ("not False = True")
else:
    print ("not False = False")

not False = True


### Loops

In [ ]:
for x in [1,2,3]:
    print(x)

1
2
3


In [ ]:
#print from 0, 1, 2, 3
y = 4
for x in range(y): # by default range start at 0
    print(x)

0
1
2
3


##### output should be 
```    
    0
    1
    2
    3
```    

In [ ]:
for word in ["scientific", "computing", "with", "python"]:
    print(word)

scientific
computing
with
python


Sometimes it is useful to have access to the indices of the values when iterating over a list. We can use the enumerate function for this:

In [ ]:
for idx, x in enumerate(range(-3,3)):
    print(idx, x)

0 -3
1 -2
2 -1
3 0
4 1
5 2


Now, we will calculate the sum from 1 to 10

In [ ]:
#set global variable ~1 line
#calculate the sum from 1 to 10, use global variable: 2 lines
sum = 0
for i in range(0,11):
    sum = sum + i
print ("sum from 1 to 10 = ", sum)

sum from 1 to 10 =  55


##### output should be:
```
sum from 1 to 10 =  55
```

A convenient and compact way to initialize lists:

In [ ]:
l1 = [x**2 for x in range(0,5)]

print(l1)

[0, 1, 4, 9, 16]


In [ ]:
i = 0

while i < 5:
    print(i)
    
    i = i + 1
    
print ("sum = ", i)
print ("done")

0
1
2
3
4
sum =  5
done


### Functions

In [ ]:
def func0():  
    #print out the "test": line 1
    print ("test")

In [ ]:
func0()

test


##### output should be:
```
test
```

In [ ]:
def func1(s):
    """
    Print a string 's' and tell how many characters it has    
    """
    print(s + " has " + str(len(s)) + " characters")

In [ ]:
help(func1)

Help on function func1 in module __main__:

func1(s)
    Print a string 's' and tell how many characters it has



In [ ]:
func1("test")

test has 4 characters


In [ ]:
def square(x):
    """
    Return the square of x.
    """
    return x ** 2

In [ ]:
square(4)

16

In [ ]:
def powers(x):
    """
    Return a few powers of x.
    """
    return x ** 2, x ** 3, x ** 4

In [ ]:
powers(3)

(9, 27, 81)

In [ ]:
x2, x3, x4 = powers(3)

In [ ]:
print(x3)

27


In [ ]:
def myfunc(x, p=2, debug=False):
    if debug:
        print("evaluating myfunc for x = " + str(x) + " using exponent p = " + str(p))
    return x**p

If we don't provide a value of the debug argument when calling the the function myfunc it defaults to the value provided in the function definition:

In [ ]:
myfunc(5)

25

In [ ]:
myfunc(5, debug=True)

evaluating myfunc for x = 5 using exponent p = 2


25

If we explicitly list the name of the arguments in the function calls, they do not need to come in the same order as in the function definition. This is called keyword arguments, and is often very useful in functions that takes a lot of optional arguments.

In [ ]:
myfunc(p=3, debug=True, x=7)

evaluating myfunc for x = 7 using exponent p = 3


343

### Classes

Python is also object-oriented programming. Like c++, understanding class is important in object-oriented programming. 
You can think of a class as a template. With the template, many objects can be created. An object is an instance of a class. The class contains attributes (variables) and methods (functions).

Each method should have an argument self as its first argument.
Example:

    def speed(self, dx, dy, dz):

Some method names have special meaning.    
Example:

    __init__: The name of the method that is invoked when the object is first created.

    __str__ : A method that is invoked when a simple string representation of the class is needed, as for example when printed.

In [ ]:
class Particle:
    """
    Simple class for representing a particle in a Cartesian coordinate system.
    """
    
    def __init__(self, x, y, z, m):
        """
        Create a new Point at x, y.
        """
        self.x = x
        self.y = y
        self.z = z
        self.m = m 
        
        
    def speed(self, dx, dy, dz):
        """
        speed up the particle by dx and dy and dz in the x and y and z direction.
        """
        ## increase the speed of the particle: 3 lines 
        self.x += dx
        self.y += dy
        self.z += dz
    
    def mass(self, dm):
        """
        increase the mass of the particle 
        """
        self.m += dm
        
    def __str__(self):
        return("particle with [%f, %f, %f, %f]" % (self.x, self.y, self.z, self.m))

To create an object (a new instance of a class):

In [ ]:
p1 = Particle(0, 0, 0, 0) # this will invoke the __init__ method in the Point class

print (p1)          # this will invoke the __str__ method

particle with [0.000000, 0.000000, 0.000000, 0.000000]


Now you have to create a second particle with the speed of 1,1,1 and the mass of 1:

In [ ]:
#create a second particle
p2 = Particle(1, 1, 1, 1)

#increase the speed of the particle 1 by 0.25 in x, 1.5 in y and 3.5 in z

print(p1)
print(p2)

particle with [0.000000, 0.000000, 0.000000, 0.000000]
particle with [1.000000, 1.000000, 1.000000, 1.000000]


##### output should be:
```
particle with [0.250000, 1.500000, 3.500000, 0.000000] 
particle with [1.000000, 1.000000, 1.000000, 1.000000] 
```

In [ ]:
%%file myParticle.py
"""
Example of a python module. Contains a variable called myMass,
a function called Mass, and a class called Particle.
"""

mymass = 0

def Mass():
    """
    Example function
    """
    return mymass
    
class Particle:
    """
    Example class.
    """

    def __init__(self):
        self.variable = mymass
        
    def setMass(self, new_value):
        """
        Set self.variable to a new value
        """
        self.variable = new_value
        
    def getMass(self):
        return self.variable


Overwriting myParticle.py


In [ ]:
#check what is created
!ls

myParticle.py  __pycache__  sample_data  score.txt


In [ ]:
import myParticle

In [ ]:
#for exercise, compare the values from variable and function:
#print "mass value from global variable (myParticle.mymass) = ", 
#print "mass value from the function (myParticle.Mass()) = ", 
print ("mass value from global varibale (myParticle.mymass) = {}".format(myParticle.mymass))
print ("mass value from the function (myParticle.Mass() = {})".format(myParticle.Mass()))

mass value from global varibale (myParticle.mymass) = 0
mass value from the function (myParticle.Mass() = 0)


##### output should be:
```
mass value from global variable (myParticle.mymass) =  0
mass value from the function (myParticle.Mass()) =  0
```

In [ ]:
help(myParticle)

Help on module myParticle:

NAME
    myParticle

DESCRIPTION
    Example of a python module. Contains a variable called myMass,
    a function called Mass, and a class called Particle.

CLASSES
    builtins.object
        Particle
    
    class Particle(builtins.object)
     |  Example class.
     |  
     |  Methods defined here:
     |  
     |  __init__(self)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  getMass(self)
     |  
     |  setMass(self, new_value)
     |      Set self.variable to a new value
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)

FUNCTIONS
    Mass()
        Example function

DATA
    mymass = 0

FILE
    /content/myParticle.py




Can you set the mass of 10 and print out?

In [ ]:
#set the particle mass as 10 
my_class = myParticle.Particle() 
#hint
#you need to set the mass and get the mass: 2 lines
my_class.setMass(10)
print(my_class.getMass())

10


##### output should be:
```
10
```

##### examples to raise error message

In [ ]:
raise Exception("description of the error")

Exception: ignored

In [ ]:
try:
    print("test")
         # generate an error: the variable test is not defined# generat 
    print(test)
except:
    print("Caught an exception")

test
Caught an exception


In [ ]:
try:
    print("test")
    # generate an error: the variable test is not defined
    print(test)
except Exception as e:
    print("Caught an exception:" + str(e))

test
Caught an exception:name 'test' is not defined


### Task 1 

There are 26 students. Use the code below to read out the score for 10 students. 
Can you write a code to print out the average and the list of students with the highest score of 20% and also the list of 50%?

In [ ]:
pip install namegenerator

In [ ]:
import random
import namegenerator as namegen

total_num = 26

with open('score.txt', 'w+') as fp:
    for i in range(total_num):
        fp.write("{}, {}".format(namegen.gen(separator='_'), 
                str(random.randint(50,100))) +"\n") 

In [ ]:
average = 0
high20 = []
high50 = []
total = []
with open("score.txt") as fp:  
   line = fp.readline()
   while line:               
        print (line)                    
        nline = line.rstrip('\n').split(',')   
        total.append((nline[0], int(nline[1])))
        average += int(nline[1])
        line = fp.readline()

print('')
total.sort(key=lambda x:-x[1])
print("Students' average grade is {}".format('%0.2f'%(average/26)))
print('')
print("Highest score of 20%: ")
print(total[:int(26*0.2)])
print('')
print("Highest score of 50%: ")
print(total[:int(26*0.5)])
print('')

flaky_ecru_dragon, 76

wheezy_turquoise_mayfly, 94

geeky_white_warthog, 70

foggy_burgundy_balinese, 55

muzzy_auburn_markhor, 59

chummy_amethyst_cuttlefish, 96

flabby_cream_cichlid, 77

lovely_pear_burmese, 71

zippy_linen_beetle, 63

squirrely_thistle_kingfisher, 72

gummy_malachite_bracke, 100

frumpy_denim_termite, 84

muzzy_brass_whippet, 89

lumpy_alizarin_lizard, 58

snippy_amaranth_tarsier, 88

messy_pear_gar, 83

breezy_lilac_setter, 76

sunny_sepia_beaver, 67

trippy_tan_hound, 74

wiggy_ochre_oyster, 54

goopy_sapphire_stoat, 83

skimpy_orange_birman, 65

chummy_sapphire_tiger, 60

thirsty_orchid_abyssinian, 87

trippy_jade_bat, 59

nerdy_heliotrope_bonobo, 60


Students' average grade is 73.85

Highest score of 20%: 
[('gummy_malachite_bracke', 100), ('chummy_amethyst_cuttlefish', 96), ('wheezy_turquoise_mayfly', 94), ('muzzy_brass_whippet', 89), ('snippy_amaranth_tarsier', 88)]

Highest score of 50%: 
[('gummy_malachite_bracke', 100), ('chummy_amethyst_cuttlefish', 96),

### Numpy

Numpy is the library package for scientific computing with Python. Basically, it deals with a N-dimensional array object.
In deep learning which we will cover later, matrix is essential so numpy will be used extensively throughout the course later. 

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])

In [ ]:
x.__class__

numpy.ndarray

#### shape

It is of importance to check the shape of the matrix to perform any operators 

In [ ]:
x.shape

(3,)

In [ ]:
x.ndim

1

In [ ]:
W = np.array([[1,2,3],[4,5,6]])

### Task 2

In [ ]:
W.shape == (2,3) # make the answer True

True

##### answer:
```
True 
```

In [ ]:
W.ndim # check the dimension of the tensor

2

#### element wise operator

In [ ]:
W = np.array([[1,2,3],[3,4,5]])

In [ ]:
X = np.array([[0,1,2],[3,4,5]])

In [ ]:
W+X

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [ ]:
W*X

array([[ 0,  2,  6],
       [ 9, 16, 25]])

#### broadcast

With this broadcast, it becomes possible to calculate betweent two matrices with different shapes. 

In [ ]:
A = np.array([[1,2],[3,4]])

In [ ]:
A*10

array([[10, 20],
       [30, 40]])

Below, two matrices A and b have different shapes. A is $2 \times 2$ and b is $1 \times 2$. In the broadcast, b can be extended to $2 \times 2$. 

A is 
$
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
$

b becomes 
$
\begin{pmatrix}
10 & 20 \\
10 & 20
\end{pmatrix}
$

A*b =
$
\begin{pmatrix}
1 \times 10 & 2 \times 20 \\
3 \times 10 & 4 \times 20
\end{pmatrix}
$ =
$
\begin{pmatrix}
10 & 40 \\
40 & 80
\end{pmatrix}
$


In [ ]:
A = np.array([[1,2],[3,4]])
b = np.array([10,20])

In [ ]:
A*b

array([[10, 40],
       [30, 80]])

#### dot product

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.dot(a,b)

32

### Task 3

A particle moving in the xy plane undergoes a displacement given by $\Delta \vec{r} = (2.0 \hat{i} + 3.0 \hat{j} + 5.0 \hat{k}) $ m as a constant force $ \vec{F} = (5.0 \hat{i} + 2.0 \hat{j})$ N acts on the particle. Calculate the workdone by $ \vec{F}$ on the particle. 

In [ ]:
r =  np.array([2.0, 3.0, 5.0])
F = np.array([5.0, 2.0, 0.0])
W = np.dot(r,F)
print(W)

16.0


#### Matrix multiplocation

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [ ]:
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

### Task 4
What would be the shape of the matrix x and b to run the code in following example?

In [ ]:
x = np.array([[1,2,3],[4,5,6]]) ## correct and fill in the blank
A = np.array([[1,2],[2,4],[3,6]])
b = np.array([[1,2], [3,4]]) ## fill in the blank 
y = np.matmul(x, A) + b

#check if the shape is correct
y.shape == (2,2)



True

##### answer:
```
True 
```